# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    form: "\n  - trigger: \"{{match}}\"\n    replace:"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d-%m-%Y"
  # ISO-Date
  - trigger: ":time"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M:%S"
  # Dates for OrgMode
  - trigger: ":odate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "[%Y-%m-%d]"


  # latex
  - trigger: "\\pd "
    form: \frac{\partial {{num}}}{\partial {{denum}}}
  - trigger: "\\pdc "
    form: \left(\frac{\partial {{num}}}{\partial {{denum}}}\right)_{{index}}
  - trigger: ":x "
    replace: "$x$"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"


  - trigger: '@tw'
    replace: 'tassilo.neubauer@web.de'
  - trigger: '@tg'
    replace: 'tassilo.neubauer@gmail.com'
  - trigger: 'gtasse'
    replace: "Grüße\n\nTassilo"
  - trigger: 'mfg'
    replace: "Mit freundlichen Grüßen\n\nTassilo Neubauer"
  - trigger: "ill"
    replace: "i’ll"
    propagate_case: true
    word: true
    
  - trigger: ":TN"
    replace: "Tassilo Neubauer"
  - trigger: ":tn"
    replace: "tassilo neubauer"
  - trigger: ":sws."
    replace: "😅"
  - trigger: "Rn"
    replace: "ℝⁿ"
  - trigger: ":github"
    replace: "git@github.com:sonofhypnos/"
  - trigger: ":windows."
    replace: ""
