# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    form: "\n  - trigger: \"{{match}}\"\n    replace:"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d-%m-%Y"
  # Dates for OrgMode
  - trigger: ":odate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "[%Y-%m-%d]"


  # latex
  - trigger: "\\pd "
    form: \frac{\partial {{num}}}{\partial {{denum}}}
  - trigger: "\\pdc "
    form: \left(\frac{\partial {{num}}}{\partial {{denum}}}\right)_{{index}}
  - trigger: ":x "
    replace: "$x$"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"


  - trigger: '@tw'
    replace: 'tassilo.neubauer@web.de'
  - trigger: '@tg'
    replace: 'tassilo.neubauer@gmail.com'
  - trigger: 'gtasse'
    replace: "Gr√º√üe\n\nTassilo"
  - trigger: 'mfg'
    replace: "Mit freundlichen Gr√º√üen\n\nTassilo Neubauer"
  - trigger: "ill"
    replace: "i‚Äôll"
    propagate_case: true
    word: true
    
  - trigger: ":TN"
    replace: "Tassilo Neubauer"
  - trigger: ":tn"
    replace: "tassilo neubauer"
  - trigger: ":sws."
    replace: "üòÖ"
  - trigger: "x(k"
    replace: "x‚ÅΩ·µè‚Åæ"
  - trigger: "a0  "
    replace: "a‚ÇÄ"
  - trigger: "s0  "
    replace: "s‚ÇÄ"
  - trigger: "d0  "
    replace: "d‚ÇÄ"
  - trigger: "f0  "
    replace: "f‚ÇÄ"
  - trigger: "g0  "
    replace: "g‚ÇÄ"
  - trigger: "h0  "
    replace: "h‚ÇÄ"
  - trigger: "j0  "
    replace: "j‚ÇÄ"
  - trigger: "k0  "
    replace: "k‚ÇÄ"
  - trigger: "l0  "
    replace: "l‚ÇÄ"
  - trigger: "q0  "
    replace: "q‚ÇÄ"
  - trigger: "w0  "
    replace: "w‚ÇÄ"
  - trigger: "e0  "
    replace: "e‚ÇÄ"
  - trigger: "r0  "
    replace: "r‚ÇÄ"
  - trigger: "t0  "
    replace: "t‚ÇÄ"
  - trigger: "z0  "
    replace: "z‚ÇÄ"
  - trigger: "u0  "
    replace: "u‚ÇÄ"
  - trigger: "i0  "
    replace: "i‚ÇÄ"
  - trigger: "o0  "
    replace: "o‚ÇÄ"
  - trigger: "p0  "
    replace: "p‚ÇÄ"
  - trigger: "y0  "
    replace: "y‚ÇÄ"
  - trigger: "x0  "
    replace: "x‚ÇÄ"
  - trigger: "c0  "
    replace: "c‚ÇÄ"
  - trigger: "v0  "
    replace: "v‚ÇÄ"
  - trigger: "b0  "
    replace: "b‚ÇÄ"
  - trigger: "n0  "
    replace: "n‚ÇÄ"
  - trigger: "m0  "
    replace: "m‚ÇÄ"
  - trigger: "a_0"
    replace: "a‚ÇÄ"
  - trigger: "s_0"
    replace: "s‚ÇÄ"
  - trigger: "d_0"
    replace: "d‚ÇÄ"
  - trigger: "f_0"
    replace: "f‚ÇÄ"
  - trigger: "g_0"
    replace: "g‚ÇÄ"
  - trigger: "h_0"
    replace: "h‚ÇÄ"
  - trigger: "j_0"
    replace: "j‚ÇÄ"
  - trigger: "k_0"
    replace: "k‚ÇÄ"
  - trigger: "l_0"
    replace: "l‚ÇÄ"
  - trigger: "q_0"
    replace: "q‚ÇÄ"
  - trigger: "w_0"
    replace: "w‚ÇÄ"
  - trigger: "e_0"
    replace: "e‚ÇÄ"
  - trigger: "r_0"
    replace: "r‚ÇÄ"
  - trigger: "t_0"
    replace: "t‚ÇÄ"
  - trigger: "z_0"
    replace: "z‚ÇÄ"
  - trigger: "u_0"
    replace: "u‚ÇÄ"
  - trigger: "i_0"
    replace: "i‚ÇÄ"
  - trigger: "o_0"
    replace: "o‚ÇÄ"
  - trigger: "p_0"
    replace: "p‚ÇÄ"
  - trigger: "y_0"
    replace: "y‚ÇÄ"
  - trigger: "x_0"
    replace: "x‚ÇÄ"
  - trigger: "c_0"
    replace: "c‚ÇÄ"
  - trigger: "v_0"
    replace: "v‚ÇÄ"
  - trigger: "b_0"
    replace: "b‚ÇÄ"
  - trigger: "n_0"
    replace: "n‚ÇÄ"
  - trigger: "m_0"
    replace: "m‚ÇÄ"
  - trigger: "Rn"
    replace: "‚Ñù‚Åø"

  - trigger: "@ukit"
    replace: "upkim@student.kit.edu"
  - trigger: ":github"
    replace: "github@github.com:sonofhypnos/"
  - trigger: "_a"
    replace: "‚Çê" 
  - trigger: "_e"
    replace: "‚Çë" 
  - trigger: "_h"
    replace: "‚Çï" 
  - trigger: "_i"
    replace: "·µ¢" 
  - trigger: "_j"
    replace: "‚±º" 
  - trigger: "_k"
    replace: "‚Çñ" 
  - trigger: "_l"
    replace: "‚Çó" 
  - trigger: "_m"
    replace: "‚Çò" 
  - trigger: "_n"
    replace: "‚Çô" 
  - trigger: "_o"
    replace: "‚Çí" 
  - trigger: "_p"
    replace: "‚Çö" 
  - trigger: "_r"
    replace: "·µ£" 
  - trigger: "_s"
    replace: "‚Çõ" 
  - trigger: "_t"
    replace: "‚Çú" 
  - trigger: "_u"
    replace: "·µ§" 
  - trigger: "_v"
    replace: "·µ•" 
  - trigger: "_x"
    replace: "‚Çì" 
  - trigger: "^a"
    replace: "·µÉ" 
  - trigger: "^b"
    replace: "·µá" 
  - trigger: "^c"
    replace: "·∂ú" 
  - trigger: "^d"
    replace: "·µà" 
  - trigger: "^e"
    replace: "·µâ" 
  - trigger: "^f"
    replace: "·∂†" 
  - trigger: "^g"
    replace: "·µç" 
  - trigger: "^h"
    replace: " ∞" 
  - trigger: "^i"
    replace: "‚Å±" 
  - trigger: "^j"
    replace: " ≤" 
  - trigger: "^k"
    replace: "·µè" 
  - trigger: "^l"
    replace: "À°" 
  - trigger: "^m"
    replace: "·µê" 
  - trigger: "^n"
    replace: "‚Åø" 
  - trigger: "^o"
    replace: "·µí" 
  - trigger: "^p"
    replace: "·µñ" 
  - trigger: "^r"
    replace: " ≥" 
  - trigger: "^s"
    replace: "À¢" 
  - trigger: "^t"
    replace: "·µó" 
  - trigger: "^u"
    replace: "·µò" 
  - trigger: "^v"
    replace: "·µõ" 
  - trigger: "^w"
    replace: " ∑" 
  - trigger: "^x"
    replace: "À£" 
  - trigger: "^y"
    replace: " ∏" 
  - trigger: "^z"
    replace: "·∂ª" 
  - trigger: "^A"
    replace: "·¥¨" 
  - trigger: "^B"
    replace: "·¥Æ" 
  - trigger: "^D"
    replace: "·¥∞" 
  - trigger: "^E"
    replace: "·¥±" 
  - trigger: "^G"
    replace: "·¥≥" 
  - trigger: "^H"
    replace: "·¥¥" 
  - trigger: "^I"
    replace: "·¥µ" 
  - trigger: "^J"
    replace: "·¥∂" 
  - trigger: "^K"
    replace: "·¥∑" 
  - trigger: "^L"
    replace: "·¥∏" 
  - trigger: "^M"
    replace: "·¥π" 
  - trigger: "^N"
    replace: "·¥∫" 
  - trigger: "^O"
    replace: "·¥º" 
  - trigger: "^P"
    replace: "·¥æ" 
  - trigger: "^R"
    replace: "·¥ø" 
  - trigger: "^T"
    replace: "·µÄ" 
  - trigger: "^U"
    replace: "·µÅ" 
  - trigger: "^V"
    replace: "‚±Ω" 
  - trigger: "^W"
    replace: "·µÇ"
  - trigger: "_1"
    replace: "‚ÇÅ" 
  - trigger: "_2"
    replace: "‚ÇÇ" 
  - trigger: "_3"
    replace: "‚ÇÉ" 
  - trigger: "_4"
    replace: "‚ÇÑ" 
  - trigger: "_5"
    replace: "‚ÇÖ" 
  - trigger: "_6"
    replace: "‚ÇÜ" 
  - trigger: "_7"
    replace: "‚Çá" 
  - trigger: "_8"
    replace: "‚Çà" 
  - trigger: "_9"
    replace: "‚Çâ" 
  - trigger: "^1"
    replace: "¬π" 
  - trigger: "^2"
    replace: "¬≤" 
  - trigger: "^3"
    replace: "¬≥" 
  - trigger: "^4"
    replace: "‚Å¥" 
  - trigger: "^5"
    replace: "‚Åµ" 
  - trigger: "^6"
    replace: "‚Å∂" 
  - trigger: "^7"
    replace: "‚Å∑" 
  - trigger: "^8"
    replace: "‚Å∏" 
  - trigger: "^9"
    replace: "‚Åπ" 
  - trigger: ":tel"
    replace: "015737027615"
